# Generated by Django 6.0.6 on 2026-09-09 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Classroom', 'Classroom'), ('Laboratory', 'Laboratory'), ('Hostel', 'Hostel'), ('Electrical', 'Electrical'), ('Internet', 'Internet'), ('Plumbing', 'Plumbing'), ('Furniture', 'Furniture'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
